# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 910f837dee7d27e1b100d01d80e691b50c74872c144a0f0ffbc0636d1c4b83119b37a3c41e0486080a5655baa1b87a9ddb632fc7d1956ceb536cbc20882b1d82

test:
  secret_key_base: 96f92ca4eadbe04c5df7b18ecf06875e6778a4107da89e57cbaf1245044513d283fb17442f226372003960ce958ec3452fbc657bb0df5fdca80c1331346f2850

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
